<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_folderKS1</name>
   <tag></tag>
   <elementGuidId>1666d144-9be5-4766-a4d3-b6b0c9931873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='More information'])[1]/following::div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>asset-type</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>folderKS1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/wkspace-root[1]/wkspace-content-container[@class=&quot;index-page subject&quot;]/wkspace-subject-index[1]/wkspace-index-page[1]/div[@class=&quot;index-page-wrapper&quot;]/div[@class=&quot;index-page-container&quot;]/div[@class=&quot;index-page-row&quot;]/div[@class=&quot;index-page-inner&quot;]/div[@class=&quot;index-page-cards&quot;]/wkspace-card-grid[1]/section[@class=&quot;card-grid-container&quot;]/div[@class=&quot;card-wrapper&quot;]/wkspace-card-light[@class=&quot;card&quot;]/div[@class=&quot;card-contents folder isEditMode&quot;]/a[1]/div[@class=&quot;asset-copy&quot;]/div[@class=&quot;asset-type&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More information'])[1]/following::div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/wkspace-card-light/div/a/div/div</value>
   </webElementXpaths>
</WebElementEntity>
