<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Maths_comet-form__checkbox</name>
   <tag></tag>
   <elementGuidId>52d19f87-6366-49f4-847a-b4494e8db979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comet-form__checkbox-checked-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/wkspace-root[1]/wkspace-content-container[@class=&quot;user-profile&quot;]/wkspace-user-profile[1]/div[@class=&quot;user-profile-wrapper&quot;]/div[@class=&quot;user-profile-container&quot;]/wkspace-content-container[1]/wkspace-user-profile-form[1]/div[@class=&quot;user-profile-form-wrapper&quot;]/div[@class=&quot;user-profile-form-container&quot;]/form[@class=&quot;ng-valid ng-touched ng-dirty&quot;]/div[@class=&quot;subjects&quot;]/div[@class=&quot;grades&quot;]/div[@class=&quot;ks&quot;]/div[@class=&quot;ks-options&quot;]/div[@class=&quot;form-group&quot;]/wkspace-checkbox-input[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/label[@class=&quot;comet-form__checkbox&quot;]/span[@class=&quot;comet-form__checkbox-visual&quot;]/svg[@class=&quot;comet-form__checkbox-checked-icon&quot;]</value>
   </webElementProperties>
</WebElementEntity>
