<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use</name>
   <tag></tag>
   <elementGuidId>0b9d1283-e282-4e11-aee9-2461755012fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>/comet/comet_assets/comet.svg#check</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/wkspace-root[1]/wkspace-content-container[@class=&quot;user-profile&quot;]/wkspace-user-profile[1]/div[@class=&quot;user-profile-wrapper&quot;]/div[@class=&quot;user-profile-container&quot;]/wkspace-content-container[1]/wkspace-user-profile-form[1]/div[@class=&quot;user-profile-form-wrapper&quot;]/div[@class=&quot;user-profile-form-container&quot;]/form[@class=&quot;ng-valid ng-touched ng-dirty&quot;]/div[@class=&quot;year-group&quot;]/div[@class=&quot;years&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-sub-group year-list&quot;]/div[@class=&quot;form-item&quot;]/wkspace-checkbox-input[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/label[@class=&quot;comet-form__checkbox&quot;]/span[@class=&quot;comet-form__checkbox-visual&quot;]/svg[@class=&quot;comet-form__checkbox-checked-icon&quot;]/use[1]</value>
   </webElementProperties>
</WebElementEntity>
